title: LCL DOORS
baseurl: /lcl-doors2022
markdown: kramdown
permalink: /:categories/:title/

# Theme settings
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs@v0.3.3
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
footer_content:

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Collections for website data
collections:
  staffers:
  modules:
#  schedules:
#  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
#  - scope:
#      path: ''
#      type: schedules
#    values:
#      layout: schedule
#  - scope:
#      path: ''
#      type: announcements
#    values:
#      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  
back_to_top: true
back_to_top_text: "Torna in cima"

plugins:
  - jekyll-seo-tag
